<a href="https://colab.research.google.com/github/Ashikur-ai/Learn-Machine-Learning/blob/main/11_Create_array_in_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

#Arrange

In [4]:
a = np.arange(0, 10)

In [5]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#Zeros and Ones

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#linspace

In [8]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

#eye

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])