<a href="https://colab.research.google.com/github/Ashikur-ai/Learn-Machine-Learning/blob/main/12_Generate_Random_Number_in_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Random numbers [0 1] uniform random dist

In [2]:
import numpy as np
np.random.rand(10)

array([0.46922666, 0.06079725, 0.08371423, 0.15112266, 0.33079402,
       0.27759928, 0.70389276, 0.98778391, 0.02609449, 0.95775424])

In [5]:
np.random.randn(3,3)

array([[-0.81006526,  0.2049901 ,  0.05312438],
       [-0.13070883, -1.46705682, -0.0426704 ],
       [ 1.17527297,  0.63113083, -0.04753461]])

In [6]:
np.random.randint(11,100, 10)

array([33, 40, 80, 91, 59, 46, 28, 75, 16, 60])