<a href="https://colab.research.google.com/github/Ashikur-ai/Learn-Machine-Learning/blob/main/13_Numpy_Array_Max%2C_Min%2C_and_Other_Attributes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Array Attributes

In [1]:
import numpy as np

In [2]:
a = np.zeros(9)

In [3]:
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

#Reshape

In [4]:
b= a.reshape(3,3)

In [5]:
b 

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
c = b.reshape(9)

In [8]:
c

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
arr = np.random.randint(1, 20, 9)

In [10]:
arr

array([ 1,  3, 17,  1, 10,  7,  3, 15,  9])

In [11]:
a = arr.reshape(3,3)

In [12]:
a

array([[ 1,  3, 17],
       [ 1, 10,  7],
       [ 3, 15,  9]])

In [13]:
a.max()

17

In [14]:
a.min()

1

In [15]:
a.argmax()

2

In [16]:
a.argmin()

0

In [17]:
a[0][0]

1

In [18]:
b = a.reshape(9,1)

In [19]:
b.size

9

In [20]:
a.size

9

In [21]:
arr.size

9

In [22]:
arr.dtype

dtype('int64')