<a href="https://colab.research.google.com/github/Ashikur-ai/Learn-Machine-Learning/blob/main/14_Arithmetic_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
list=[16, 12, 3, 4, 3]

In [4]:
a = np.array(list)

In [5]:
a

array([16, 12,  3,  4,  3])

In [6]:
arr = np.exp(a)

In [7]:
arr

array([8.88611052e+06, 1.62754791e+05, 2.00855369e+01, 5.45981500e+01,
       2.00855369e+01])

In [8]:
np.sin(a)

array([-0.28790332, -0.53657292,  0.14112001, -0.7568025 ,  0.14112001])

In [9]:
np.log(arr)

array([16., 12.,  3.,  4.,  3.])

In [10]:
np.mean(arr)

1809792.016230151